Web/Controllers/ExchangeRateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BCC.Model.Models;
using BCC.Core;
using System.Reflection;
using  Microsoft.Extensions.Logging;
using Web.Models;
using OfficeOpenXml;
using OfficeOpenXml.Table;
using System.Data;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Web.Controllers
{
    public class ExchangeRateController : Controller
    {
        #region Dependencies
        private readonly BCCContext _context;
        private readonly IPresentationManager _presentationManager;
        private readonly ILogger<ExchangeRateController> _logger;
        private const string XlsxContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        #endregion

        private readonly string _version;
        public ExchangeRateController(BCCContext context, IPresentationManager presentationManager, ILogger<ExchangeRateController> logger)
        {
            _logger = logger;
            _context = context;
            _presentationManager = presentationManager;
            _version = Assembly.GetExecutingAssembly().GetName().Version.ToString();
        }

        public IActionResult Index()
        {
            ViewBag.version = _version;
            ViewBag.title = "Exchange Rates";
            return View();
        }
        public IActionResult BankTickets()
        {
            ViewBag.version = _version;
            List<BankConnector> banks = _context.BankConnector.ToList();
            return View(viewName: "~/Views/ExchangeRate/BankTickets.cshtml", model: banks);
        }

        public IActionResult BestTickets()
        {
            ViewBag.version = _version;
            return View(viewName: "~/Views/ExchangeRate/BestTickets.cshtml");
        }

        public IActionResult Recommendations()
        {
            ViewBag.version = _version;
            return View(viewName: "~/Views/ExchangeRate/Recommendations.cshtml");
        }

        public IActionResult Wholesales()
        {
            ViewBag.version = _version;
            return View(viewName: "~/Views/ExchangeRate/Wholesales.cshtml");
        }

        [HttpGet]
        public IActionResult MixTickets()
        {
            ViewBag.version = _version;
            List<CurrencyMetadata> meta = _context.CurrencyMetadata.ToList();
            List<BankConnector> banks = _context.BankConnector.ToList();
            return View(viewName: "~/Views/ExchangeRate/MixTickets.cshtml",model: Tuple.Create(banks,meta));
        }

        [HttpGet]
        public IActionResult Overview()
        {
            /*string json = HttpContext.Session.GetString(HttpContext.Session.Id);
            var sessionData = JsonConvert.DeserializeObject(json??"[]");
            string sesionJson = JsonConvert.SerializeObject(sessionData);
            */

            BCCSession session =  GetCurrentSession();
            string overviewsJson = "[]";
            if (session.OverviewModels != null)
            {
                overviewsJson = JsonConvert.SerializeObject(session.OverviewModels);
            }
            
            ViewBag.version = _version;
            List<CurrencyMetadata> meta = _context.CurrencyMetadata.ToList();
            return View(viewName: "~/Views/ExchangeRate/Overview.cshtml", model: new Tuple<List<CurrencyMetadata>,string>( meta,overviewsJson));
        }



       [HttpGet]
        public IActionResult CurrencyPrice()
        {
            ViewBag.version = _version;
            
            List<CurrencyMetadata> meta = _context.CurrencyMetadata.ToList();
            return View(viewName: "~/Views/ExchangeRate/CurrencyPrice.cshtml", model: meta);
        }

        [HttpGet]
        public IActionResult CurrencyTimeline()
        {
            List<CurrencyMetadata> meta = _context.CurrencyMetadata.ToList();
            return View(viewName: "~/Views/ExchangeRate/CurrencyTimeline.cshtml", model: meta);
        }


        [HttpGet]
        public PartialViewResult OverviewControl([FromQuery]string isoName="AUD",[FromQuery] int interval=7,[FromQuery] bool isBuy=true)
        {

            ViewBag.tableType = isBuy ? "Buy" : "Sell";
            var overviewModel = new OverviewModel() { Currency = isoName, Interval = interval, IsBuy = isBuy };
            var table = _presentationManager.SingleCurrencyRecommendation(isoName);
            return PartialView(viewName: "~/Views/ExchangeRate/OverviewControl.cshtml", model: new Tuple<DataTable,OverviewModel>(table,overviewModel));
        }

        [HttpGet]
        public IActionResult BankMargin()
        {
            ViewBag.version = _version;
            BCCSession session = GetCurrentSession();
            string marginsJson = "[]";

            if(session.BankMarginModels != null)
            {
                marginsJson = JsonConvert.SerializeObject(session.BankMarginModels);
            }
            List<CurrencyMetadata> meta = _context.CurrencyMetadata.ToList();
            List<BankConnector> banks = _context.BankConnector.Where(x=> x.BankShortName != "CNB" ).ToList();
            return View(viewName: "~/Views/ExchangeRate/BankMargin.cshtml",model: new Tuple<List<CurrencyMetadata>, List<BankConnector>, string> (meta, banks,marginsJson));
        }

        [HttpPost]
        public OkResult UpdateSession([FromBody]List<OverviewModel> data)
        {

            var json = JsonConvert.SerializeObject(data);
            HttpContext.Session.SetString(HttpContext.Session.Id, json);

            return Ok();
        }

        [HttpPost]
        public OkResult UpdateOverviewSession([FromBody] List<OverviewModel> data)
        {

            var session = GetCurrentSession();
            session.OverviewModels = data;
            string sessionJson = JsonConvert.SerializeObject(session);
            HttpContext.Session.SetString(HttpContext.Session.Id, sessionJson);
            return Ok();
        }

        [HttpPost]
        public OkResult UpdateBankMarginSession([FromBody] List<BankMarginModel> data)
        {
           
            var session = GetCurrentSession();
            session.BankMarginModels = data;
            string sessionJson = JsonConvert.SerializeObject(session);
            HttpContext.Session.SetString(HttpContext.Session.Id, sessionJson);
            return Ok();
        }

        private BCCSession GetCurrentSession() {
            string json = HttpContext.Session.GetString(HttpContext.Session.Id);
            return JsonConvert.DeserializeObject<BCCSession>( string.IsNullOrWhiteSpace(json)? "{}": json, new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore});
        }
       

       
        

    }
}

Web/Controllers/UtillitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class UtillitiesController : Controller
    {

        [HttpGet("Utillity/")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Index()
        {
            return View(viewName: "~/Views/Utillities/DayDivision.cshtml");
        }

        [HttpGet("Utillity/DayDivisionComponent")]
        [ResponseCache(Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult DayDivisionComponent([FromQuery]DateTime start, [FromQuery]DateTime end, [FromQuery] decimal value)
        {
            if (start == null || start == DateTime.MinValue) start = DateTime.Now;
            if (end == null || end == DateTime.MinValue) end = DateTime.Now;
            int days = (end - start).Days + 1;
            var model = new DayDivisionModel()
            {
                Start = start,
                End = end,
                Value = value,
                Days = days,
            };
            if (days > 0)
            {
                decimal dailyAverage = value / days;
                model.Average = dailyAverage;
                var result = DayDivision.YearlyIntervals(start, end);
                model.Data = new List<DayDivisionData>(result.Count);
                foreach (DayDivision.DayDivisionSpan span in result)
                {
                    model.Data.Add(new DayDivisionData()
                    {
                        From = span.From,
                        To = span.To,
                        Value = (int)Math.Abs((span.From - span.To).Days + 1) * dailyAverage,

                    });
                }
            }
            else
            {
                model.Error = $"Span between the {start} and {end} is lower than a day.";
            }
            return PartialView(model: model, viewName: "~/Views/Utillities/DayDivisionComponent.cshtml");
        }

        public class DayDivision
        {

            public DayDivision(DateTime start, DateTime end, decimal value)
            {
                int days = end.Subtract(start).Days;

            }
            public static List<DayDivisionSpan> YearlyIntervals(DateTime start, DateTime end)
            {
                List<DayDivisionSpan> spans = new List<DayDivisionSpan>();
                if (end < start) throw new ArgumentException("End time can not be lower than start.");

                while (new DateTime((long)Math.Abs((end - start).Ticks)).Year - 1 >= 1)
                {

                    spans.Add(new DayDivisionSpan()
                    {
                        From = start,
                        To = new DateTime(start.Year, 12, 31)
                    });
                    start = new DateTime(start.Year + 1, 1, 1);
                }
                spans.Add(new DayDivisionSpan()
                {
                    From = start,
                    To = end,
                });

                return spans;
            }

            public class DayDivisionSpan
            {
                public DateTime From { get; set; }
                public DateTime To { get; set; }
            }

        }
        public class DayDivisionModel
        {
            public string Error { get; set; }
            public bool IsOk => Error == null;

            public DateTime Start { get; set; }
            public DateTime End { get; set; }
            public decimal Value { get; set; }
            public int Days { get; set; }
            public decimal Average { get; set; }
            public List<DayDivisionData> Data { get; set; }

        }

        public class DayDivisionData
        {
            public DateTime From { get; set; }
            public DateTime To { get; set; }
            public decimal Value { get; set; }
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.min.js"></script>
    <script src="~/js/chartjs-plugin-annotation.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" crossorigin="anonymous" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="></script>

</head>
<body>


   
    <div class="d-flex" id="wrapper">
        
        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Stats</div>
            <div class="list-group list-group-flush">

                <!--
    <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="BankTickets">Bank tickets</a>
    <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="Recommendations">Recommendations</a>
    <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="Wholesales">Wholesales</a>
    <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="BestTickets">Best tickets</a>
    <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="CurrencyPrice">Currency price</a>
    <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="CurrencyTimeline">Currency timeline</a>
    -->
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="Overview"><strong>Overview</strong></a>
                <a class="nav-link text-dark" asp-area="" asp-controller="ExchangeRate" asp-action="BankMargin"><strong>Margin</strong></a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="ExchangeRate" asp-action="MixTickets">Mix</a>


            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->


        <div id="page-content-wrapper">
            <header>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="btn btn-outline-dark" id="menu-toggle">Stats sidebar</div>

                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExchangeRate" asp-action="Overview"><strong>Overview</strong></a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExchangeRate" asp-action="BankMargin"><strong>Margin</strong></a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExchangeRate" asp-action="Index">Introduction</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Utillities" asp-action="Index">Utillity</a>

                        </div>
                    </div>
                </nav>
            </header>





            <div class="container-fluid p-4">
                <!-- /#page-content-wrapper -->
               
                @RenderBody()
            </div>
        </div>
    </div>
    <footer class="footer  bg-white border-top border-info" >
        <div class="container">
            <div class="row">
                <div class="col justify-content-center d-flex">
                    <span class="text-muted"><strong>Contact: </strong>Michael Melena | michael.melena@tul.cz</span>
                </div>
                <div class="col justify-content-center d-flex">
                    <span class="text-muted"><strong>Version:</strong> @(ViewBag.version != null? ViewBag.version.ToString():"Unavailable")</span>
                </div>
            </div>
            
        </div>
            
                    
                    
                
            
        
    </footer>







    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
    <script src="~/js/site.js"></script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
    @RenderSection("Scripts", required: false)

</body>
    </html>